version: 2.1

orbs:
  slack: circleci/slack@2.5.1

executors:
  codepush_executor:
    working_directory: ~/voom
    shell: /bin/bash --login -o pipefail
    docker:
      - image: circleci/node:10

commands:
  notify_slack_if_deploy_succeeded:
    description: Notify people of successful deploys
    parameters:
      environment:
        description: Which environment is being deployed to
        type: string
        default: unspecified_environment
      git_deploy_sha_begin:
        description: Begin git sha
        type: string
      git_deploy_sha_end:
        description: End git sha
        type: string
      git_deployed_diff:
        description: Git diff for deploy
        type: string
    steps:
      - run:
          description: "show stuff"
          command: |
            echo "<< parameters.environment >> <https://github.com/voomflights/ponton/compare/$(echo << parameters.git_deploy_sha_begin >>)...$(echo $GIT_DEPLOY_SHA_END) $(echo $GIT_DEPLOYED_DIFF)"

jobs:
  hydrate_bash_environment:
    parallelism: 1
    executor: codepush_executor
    steps:
      - checkout:
          path: ~/voom

      - deploy:
          name: Deploy to Heroku
          command: ./bin/hydrate_bash_environment

      - run: echo 'export OTHER_JOB=probablY_not' >> $BASH_ENV
      - run: echo $BASH_ENV
      - run: cat $BASH_ENV > /var/tmp/bash_env
      - persist_to_workspace:
          root: /var/tmp
          paths:
            - bash_env

  slack_notification:
    parallelism: 1
    executor: codepush_executor
    steps:
      - attach_workspace:
          at: /var/tmp/

      - run: cat /var/tmp/bash_env >> $BASH_ENV

      - notify_slack_if_deploy_succeeded:
          environment: "staging"
          git_deploy_sha_begin: $GIT_DEPLOY_SHA_BEGIN
          git_deploy_sha_end: $GIT_DEPLOY_SHA_END
          git_deployed_diff: $GIT_DEPLOYED_DIFF
      - run: echo $BASH_ENV
      - run: echo $GIT_ATTRIBUTION
      - run: echo $OTHER_JOB

workflows:
  voom:
    jobs:
      - hydrate_bash_environment:
          filters:
            branches:
              only:
                - master
      - slack_notification:
          requires:
            - hydrate_bash_environment
          filters:
            branches:
              only:
                - master
